import express from 'express';
const router = express.Router();
import {postData} from '../Controllers/index.js';
import { signup ,signin } from '../Controllers/auth.js';
import { filterData ,predictCollege} from '../Controllers/index.js';
router.post('/postdata',postData);
router.post('/filterdata',filterData);
router.post('/signup', signup);
router.post('/signin', signin);
router.post('/predictColleges',predictCollege);
export default router;